# -*- coding: utf-8 -*-
"""Task-1 (Customer Personality Analysis).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aMl0oHFm3JlavZfdH3lCWuvkulCIPOOE

# **Table of Contents**

1. Problem statement
1.1. Introduction
1.2. Dataset Features
2. Import Libraries and Data
3. Handling Missing Values
4. Feature Engineering
5. Data Analysis and Visualization

# **Problem_Statement**

**Customer Personality Analysis** is a detailed analysis of a company’s ideal customers. It helps a business to better understand its customers and makes it easier for them to modify products according to the specific needs, behaviors and concerns of different types of customers.

Customer personality analysis helps a business to modify its product based on its target customers from different types of customer segments. For example, instead of spending money to market a new product to every customer in the company’s database, a company can analyze which customer segment is most likely to buy the product and then market the product only on that particular segment.

# **Dataset_Features**

**People:**

* `ID`: Customer's unique identifier
* `Year_Birth`: Customer's birth year
* `Education`: Customer's education level
* `Marital_Status`: Customer's marital status
* `Income`: Customer's yearly household income
* `Kidhome`: Number of children in customer's household
* `Teenhome`: Number of teenagers in customer's household
* `Dt_Customer`: Date of customer's enrollment with the company
* `Recency`: Number of days since customer's last purchase
* `Complain`: 1 if the customer complained in the last 2 years, 0 otherwise

**Products:**

* `MntWines`: Amount spent on wine in last 2 years
* `MntFruits`: Amount spent on fruits in last 2 years
* `MntMeatProducts`: Amount spent on meat in last 2 years
* `MntFishProducts`: Amount spent on fish in last 2 years
* `MntSweetProducts`: Amount spent on sweets in last 2 years
* `MntGoldProds`: Amount spent on gold in last 2 years

**Promotion:**

* `NumDealsPurchases`: Number of purchases made with a discount
* `AcceptedCmp1`: 1 if customer accepted the offer in the 1st campaign, 0 otherwise
* `AcceptedCmp2`: 1 if customer accepted the offer in the 2nd campaign, 0 otherwise
* `AcceptedCmp3`: 1 if customer accepted the offer in the 3rd campaign, 0 otherwise
* `AcceptedCmp4`: 1 if customer accepted the offer in the 4th campaign, 0 otherwise
* `AcceptedCmp5`: 1 if customer accepted the offer in the 5th campaign, 0 otherwise
* `Response`: 1 if customer accepted the offer in the last campaign, 0 otherwise

**Place:**

* `NumWebPurchases`: Number of purchases made through the company’s website
* `NumCatalogPurchases`: Number of purchases made using a catalogue
* `NumStorePurchases`: Number of purchases made directly in stores
* `NumWebVisitsMonth`: Number of visits to company’s website in the last month

# **Importing Libraries**
"""

# importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import plotly.express as px
import plotly.io as pio

# Load Data
data = pd.read_csv('/content/marketing_campaign.csv',sep="\t")

# Checkhing how many rows and columns are present
data.shape

# basic information
# First rows
data.head()

# Last rows
data.tail()

# Info
data.info()

# Checkhing null values
data.isnull().sum()

# droping the null values
data.dropna(inplace=True)

# Checking the duplicate values
data.duplicated().sum()

"""I started by loading the customer personality dataset and did a quick scan to see how many rows and columns it had. Then I took a look at the first and last few entries to get a feel for what kind of data I’m working with. After that, I checked for any missing values and cleaned those up by dropping the rows that had gaps. I also made sure there weren’t any duplicate entries floating around — turns out there weren’t many, so that was easy to handle.

Now the dataset is clean and ready for analysis. This step is important because it sets the foundation for everything that comes next. With clean data, I can start exploring patterns — like how age or income might influence spending habits, or whether certain personality traits align with specific product preferences. These insights will help build smarter customer segments and make marketing strategies more targeted and effective.

# **Data Preprocessing and Feature Engineering**
"""

data.columns

drop = 'ID'
data.drop(columns=[drop], inplace=True)
data.head()

data['Age'] = 2025 - data['Year_Birth']

def categorize(age):
    if age < 13:
        return 'Child'
    elif 13 <= age < 18:
        return 'Teen'
    elif 18 <= age < 35:
        return 'Young Adult'
    elif 35 <= age < 65:
        return 'Adult'
    else:
        return 'Senior'

data['Age_Category'] = data['Age'].apply(categorize)

data['Age_Category'] = pd.Categorical(data['Age_Category'],
                                       categories=['Child', 'Teen', 'Young Adult', 'Adult', 'Senior'],
                                       ordered=True)

data[['Year_Birth', 'Age', 'Age_Category']].head()

drop = 'Year_Birth'
data.drop(columns=[drop], inplace=True)
data.head()

# changing education & marital_status data type into category
data['Education'] = data['Education'].astype('category')
data['Marital_Status'] = data['Marital_Status'].astype('category')
data['Kidhome']=data['Kidhome'].astype('category')
data['Teenhome']=data['Teenhome'].astype('category')

# coverting Dt_customer into datetime
data['Dt_Customer']=pd.to_datetime(data['Dt_Customer'],format='%d-%m-%Y')

# changing Income Float data type into int
data['Income'] = data['Income'].astype('int')

data.dtypes

data['Year'] = data['Dt_Customer'].dt.year
data['Year'].value_counts()

data.head()

drop = ['Dt_Customer','Year']
data.drop(columns=drop, inplace=True)
data.head()

data.columns

data.dtypes

minRecency = data['Recency'].min()
maxRecency = data['Recency'].max()
meanRecency = data['Recency'].mean()
print("Minimum Recency:", minRecency)
print("Maximum Recency:", maxRecency)
print("Mean Recency:", meanRecency)

bins = [0, 7, 30, float('inf')]
labels = ['< Weak', '< Month', '>']
data['Recency'] = pd.cut(data['Recency'], bins=bins, labels=labels, right=False)
data.head()

data['Recency'].value_counts()

drop = 'Recency'
data.drop(columns=drop, inplace=True)
data.head()

drop = 'Age'
data.drop(columns=drop, inplace=True)
data.head()

data['AcceptedCmp3'].value_counts()

data['AcceptedCmp1'] = data['AcceptedCmp1'].astype(bool)
data['AcceptedCmp2'] = data['AcceptedCmp2'].astype(bool)
data['AcceptedCmp3'] = data['AcceptedCmp3'].astype(bool)
data['AcceptedCmp4'] = data['AcceptedCmp4'].astype(bool)
data['AcceptedCmp5'] = data['AcceptedCmp5'].astype(bool)

data['Complain'].value_counts()

drop = 'Complain'
data.drop(columns=drop, inplace=True)
data.head()

data['Loss'] = data['Z_CostContact'] > data['Z_Revenue']
Loss = data[data['Loss']]
Loss

drop = 'Loss'
data.drop(columns=drop, inplace=True)
data.head()

data['Z_Revenue'].value_counts()

data['Z_CostContact'].value_counts()

drop = ['Z_CostContact','Z_Revenue']
data.drop(columns=drop, inplace=True)
data.head()

data['Response'] = data['Response'].astype(bool)

data.dtypes

for column, dtype in data.dtypes.items():
    if pd.api.types.is_numeric_dtype(dtype):
        print(f"{column}: Numerical")
    elif pd.api.types.is_categorical_dtype(dtype):
        print(f"{column}: Categorical")
    elif pd.api.types.is_bool_dtype(dtype):
        print(f"{column}: Boolean")
    else:
        print(f"{column}: Other")

print("Numerical Columns:")
print(data.select_dtypes(include='number').columns.tolist())

data['Income'] = data['Income'].astype(int)

"""**Insight**:-

I started by cleaning up the customer personality dataset to make it analysis-ready. First, I removed unnecessary columns like ID and Year_Birth, then calculated each customer's age and grouped them into meaningful categories like Child, Teen, Young Adult, Adult, and Senior. This helps in understanding customer behavior across different life stages.

Next, I converted several columns—like education level, marital status, and household composition—into categorical types to make segmentation easier. I also transformed the customer enrollment date into a proper datetime format and extracted the year, which gives insight into customer tenure. After analyzing the Recency feature (how recently a customer interacted), I binned it into simplified categories to better interpret engagement levels.

I cleaned up campaign response columns by converting them into boolean values, making it easier to track who responded to which offers. I also flagged customers where marketing costs exceeded revenue, helping identify potential inefficiencies. Finally, I reviewed all column types to ensure consistency and confirmed which features are numerical, categorical, or boolean.

All these steps weren’t just about cleaning data—they were about reshaping it to reflect real customer behavior. Now the dataset is primed for deeper analysis, whether it’s visualizing spending patterns, clustering customer segments, or building predictive models that drive smarter marketing decisions.

# **Exploratory Data Analysis (EDA)**

**What is the distribution of educational levels among customers, and how might this influence marketing strategies or product positioning?**
"""

print("Categorical Columns:")
print(data.select_dtypes(include='category').columns.tolist())

labels = data['Education'].value_counts().index
sizes = data['Education'].value_counts().values
colors = ['#4CAF50', '#2196F3', '#FFC107', '#FF5722', '#9C27B0']

plt.figure(figsize=(8, 8))
plt.pie(sizes, labels=labels, colors=colors, startangle=90, counterclock=False, autopct='%1.1f%%')

centre_circle = plt.Circle((0, 0), 0.70, fc='white')
fig = plt.gcf()
fig.gca().add_artist(centre_circle)
plt.show()

"""**Insights**:-

By visualizing the distribution of education levels using a donut chart,we uncovered that the majority of your customer base—over 50%—has completed graduation, followed by smaller segments with PhDs, master’s degrees, and other qualifications. This tells us that your audience is largely well-educated, which can influence how you communicate with them. For example, marketing messages can be more data-driven or intellectually engaging, and product offerings can be positioned with a focus on quality, innovation, or long-term value. Understanding this breakdown also helps tailor campaigns to niche groups, like promoting advanced learning tools or luxury products to PhD holders, while offering practical solutions to those with basic education.

**How are customers distributed across different marital statuses, and what does this tell us about their potential lifestyle preferences or purchasing behavior?**
"""

labels = data['Marital_Status'].value_counts().index
counts = data['Marital_Status'].value_counts().values

plt.stem(labels, counts, markerfmt='go', basefmt=" ", linefmt='b-')

plt.ylabel('            Count')
plt.show()

"""**Insights**:-

By plotting the distribution of marital statuses, we have revealed that the majority of your customers are either married or in a relationship, followed by a significant number who are single. Smaller groups include divorced, widowed, and some unconventional entries like “YOLO” and “Absurd,” which might reflect playful or non-traditional responses. This breakdown is more than just demographic trivia—it gives you clues about lifestyle dynamics. For example, married or partnered individuals might be more inclined toward family-oriented products or services, while singles could respond better to experiences or self-care offerings.
"""

data['Kidhome'].value_counts()

!pip install squarify
import squarify

"""**How many customers have children living at home, and what does this reveal about their potential lifestyle needs or purchasing behavior?**"""

labels = data['Kidhome'].value_counts().index
sizes = data['Kidhome'].value_counts().values

squarify.plot(sizes=sizes, label=labels, alpha=0.8)
plt.show()

"""**Insights**:-

The treemap showing the number of children living at home offers a quick snapshot of household dynamics. A large portion of customers have no children at home, while smaller segments have one or two. This breakdown is valuable for understanding lifestyle needs—households without kids may lean toward personal luxury, travel, or entertainment, while those with children might prioritize family-friendly products, educational services, or convenience-based solutions. Recognizing these patterns helps shape more relevant marketing strategies and product offerings that align with the daily realities of each group.

**What does the distribution of teenagers at home reveal about customer household dynamics and potential marketing opportunities?**
"""

labels = data['Teenhome'].value_counts().index.astype(str)
sizes = data['Teenhome'].value_counts().values
colors = ['#FF9999', '#66B3FF', '#99FF99']

plt.pie(sizes, labels=labels, colors=colors, startangle=90, autopct='%1.1f%%')
plt.show()

"""**Insight**:-


The pie chart showing the number of teenagers living at home gives a clear picture of household composition across your customer base. A majority of customers have no teenagers at home, while smaller segments have one or two. This insight is useful for understanding lifestyle priorities—households without teens may be more flexible in spending and time, while those with teens might be focused on education, tech products, or family-oriented services. Recognizing these differences allows for more targeted marketing strategies, such as promoting youth-focused campaigns to families with teens or offering solo experiences to those without

**How is the customer base distributed across different age categories, and what does this reveal about their potential needs and preferences?**
"""

labels = data['Age_Category'].value_counts().index
counts = data['Age_Category'].value_counts().values

plt.bar(labels, counts, color=['#4CAF50', '#2196F3', '#FFC107'])

plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

"""**Insight**:-


The bar chart showing age category distribution reveals a strong concentration of customers in the "Adult" segment, followed by a sizable group of "Seniors." "Young Adults" form a much smaller portion, while "Children" and "Teens" are virtually absent. This age profile suggests that most customers are mature individuals likely focused on stability, long-term value, and possibly family-oriented products. Seniors may lean toward comfort, healthcare, or retirement-related services, while the smaller group of young adults might be more responsive to tech, lifestyle, or aspirational offerings.

**How do acceptance rates vary across different marketing campaigns, and what does this reveal about their relative effectiveness?**
"""

acceptanceRates = {}

for column in ['AcceptedCmp1', 'AcceptedCmp2', 'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5']:
    true = data[column].sum()
    false = len(data[column]) - true
    total = true + false
    acceptanceRate = true / total
    acceptanceRates[column] = acceptanceRate

for campaign, rate in acceptanceRates.items():
    print(f"{campaign}: {rate:.4f}")

d = pd.DataFrame(list(acceptanceRates.items()), columns=['Campaign', 'Acceptance Rate'])

colors = ['#FFB3B3', '#B3FFB3', '#B3B3FF', '#FFB3E6', '#FFF9B3']

d['Campaign'] = ['Campaign ' + str(i + 1) for i in range(len(d))]
plt.bar(d['Campaign'], d['Acceptance Rate'], color=colors)

plt.ylabel('Acceptance Rate')
plt.tight_layout()
plt.show()

"""**Insights**:-

The bar chart comparing acceptance rates across five campaigns highlights clear differences in performance. Campaigns 3, 4, and 5 show the highest acceptance rates, suggesting they resonated better with the target audience—possibly due to more appealing offers, better timing, or stronger messaging. Campaign 1 performed moderately, while Campaign 2 had the lowest acceptance rate, indicating it may need reevaluation or a strategic overhaul. This comparison is crucial for understanding what works and what doesn’t, helping to refine future campaigns by focusing on elements that drive engagement and conversion.

**What does the relationship between income and spending on wine reveal about customer purchasing behavior and potential targeting strategies?**
"""

data['Response'].value_counts()

falseR = data['Response'].value_counts().get(False, 0)
trueR = data['Response'].value_counts().get(True, 0)

totalR = falseR + trueR
responseRate = (trueR / totalR) * 100 if totalR > 0 else 0
print(f'Response Rate: {responseRate:.2f} %')

plt.figure(figsize=(10, 6))
sns.scatterplot(data=data, x='Income', y='MntMeatProducts', alpha=0.6)
plt.title('Income vs. Spending on Wine (MntWines)')
plt.xlabel('Income')
plt.ylabel('Spending on Wine (MntWines)')
plt.show()

"""**Insights**:-

The scatter plot mapping income against wine spending reveals a few key patterns. Most customers fall within a moderate income range and spend modestly on wine, suggesting that wine consumption is relatively consistent across middle-income groups. However, there are a few outliers—some individuals with very high income who spend little, and others with lower income who spend significantly more. This indicates that wine purchasing isn’t strictly tied to income level; personal preferences, lifestyle, or cultural factors may play a role. For marketing, this means targeting wine promotions based solely on income might miss key segments.
"""

pio.renderers.default = 'colab'

"""**What does the distribution of customer education levels reveal about the overall profile and potential expectations of the audience?**"""

fig = px.bar(data['Education'].value_counts(),
             color=data['Education'].value_counts().index,
             template='plotly_dark',
             text_auto=True,
             labels={'value':'count'},
             title='Distribution of Customer Education Level'
            )
fig.write_html("education_distribution.html")
from IPython.display import display, HTML
display(HTML("education_distribution.html"))

"""**Insights**:-

The bar chart showing education levels paints a clear picture of the customer base: the overwhelming majority have completed graduation, while other categories like PhD, Master’s, and Basic education are either minimal or absent. This suggests that the audience is largely well-educated, likely to value informed decision-making, quality products, and thoughtful communication. It also implies that marketing strategies can lean into more sophisticated messaging—highlighting product features, long-term benefits, or data-backed claims.

**How does the number of children at home influence average household income, and what can this tell us about customer financial capacity?**
"""

income_by_kids=data.groupby('Kidhome')['Income'].mean()
income_by_kids

fig = px.bar(income_by_kids,
             color=income_by_kids.index,
             template='plotly_dark',
             text_auto=True,
             labels={'value':'AVG'},
             title='Distribution of income by kids'
            )
fig.write_html("income_by_kids.html")
from IPython.display import display, HTML
display(HTML("income_by_kids.html"))

"""**Insights**:-

The bar chart comparing average income across households with different numbers of children reveals a clear trend: individuals without children at home tend to have significantly higher average income than those with one or two kids. This suggests that child-free households may have more disposable income, potentially making them more receptive to premium products, travel, or lifestyle upgrades. In contrast, households with children might prioritize value, practicality, or family-focused offerings. Understanding this income disparity helps tailor marketing strategies—whether it's positioning luxury items for higher-income segments or crafting bundled deals and savings for families.

**How does the number of teenagers at home relate to average household income, and what can this reveal about financial dynamics across different family structures?**
"""

income_by_teenager=data.groupby('Teenhome')['Income'].mean()
fig = px.bar(income_by_teenager,
             color=income_by_teenager.index,
             template='plotly_dark',
             text_auto=True,
             labels={'value':'AVG'},
             title='Distribution of income by teenager'
            )
fig.write_html("income_by_teenager.html")
from IPython.display import display, HTML
display(HTML("income_by_teenager.html"))

"""**Insights**:-

The bar chart showing average income by number of teenagers at home reveals a subtle but consistent upward trend. Households with no teenagers have the lowest average income, while those with one or two teens show slightly higher earnings. This pattern may reflect the financial maturity of families with older children—possibly dual-income households or individuals further along in their careers. It also suggests that families with teenagers might have more purchasing power, making them viable targets for products and services related to education, technology, or lifestyle upgrades

**How does educational attainment influence average income, and what does this reveal about the financial profile of different customer segments?**
"""

income_by_Education=data.groupby('Education')['Income'].mean()
fig = px.bar(income_by_Education,
             color=income_by_Education.index,
             template='plotly_dark',
             text_auto=True,
             labels={'value':'AVG'},
             title='Distribution of income by education'
            )
fig.write_html("income_by_Education.html")
from IPython.display import display, HTML
display(HTML("income_by_Education.html"))

"""**Insights**:-

The bar chart comparing average income across education levels shows a clear upward trend: individuals with higher education—especially those holding PhDs and Master’s degrees—tend to earn significantly more than those with basic or intermediate qualifications. Graduation marks a strong middle ground, while Basic education correlates with the lowest average income. This pattern reinforces the link between academic achievement and earning potential, offering valuable context for customer segmentation. It suggests that higher-educated customers may be more receptive to premium products, investment opportunities, or long-term value propositions, while those with lower education levels might prioritize affordability and practicality.

**How does marital status influence average income, and what insights can be drawn about financial behavior across different relationship categories?**
"""

income_by_martial_status=data.groupby('Marital_Status')['Income'].mean()
fig = px.bar(income_by_martial_status,
             color=income_by_martial_status.index,
             template='plotly_dark',
             text_auto=True,
             labels={'value':'AVG'},
             title='Distribution of income by marital status'
            )
fig.write_html("income_by_martial_status.html")
from IPython.display import display, HTML
display(HTML("income_by_martial_status.html"))

"""**Insights**:-

The bar chart comparing average income across marital statuses reveals notable variation. Individuals labeled as “Absurd” have the highest average income, followed by widowed and divorced customers. Those who are married, single, or in a relationship (“Together”) show relatively similar income levels, while categories like “Alone” and “YOLO” fall on the lower end. This suggests that unconventional or independent lifestyles may correlate with higher earnings, possibly due to fewer dependents or more career flexibility. On the other hand, traditional family structures might reflect more stable but moderate income levels.
"""

numerical_cols = data.select_dtypes(include='number').columns
correlation_matrix = data[numerical_cols].corr()

plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm' ,fmt=".2f")
plt.show()

"""**Insights**:-

The heatmap of the correlation matrix reveals how different consumer and demographic variables interact. Strong positive correlations are visible among various spending categories—like wine, meat, and gold products—suggesting that customers who spend more in one area tend to spend more across others. Income shows moderate positive correlation with high-end purchases like wine and gold, indicating that wealthier customers lean toward premium products. Meanwhile, web and catalog purchases correlate with spending, hinting at a preference for remote shopping among higher-value customers. On the flip side, frequent web visits without purchases may signal browsing behavior or low conversion.

**What does the distribution of different purchase types reveal about customer engagement and campaign effectiveness?**
"""

amounts=data.columns.tolist()[8:14]
data[amounts].sum()

type_of_purchases=data.columns.tolist()[14:18]
fig = px.bar(data[type_of_purchases].sum(),
             color=type_of_purchases,
             template='plotly_dark',
             text_auto=True,
             labels={'value':'count'},
             title='Distribution of purchases'
            )
fig.write_html("purchases_distribution.html")
from IPython.display import display, HTML
display(HTML("purchases_distribution.html"))

"""**Insights**:-

The bar chart comparing purchase-related metrics shows a clear dominance of store purchases and web visits, indicating that customers are highly engaged through physical retail and online browsing. However, the acceptance rates for campaigns (AcceptedCmp3 and AcceptedCmp4) are significantly lower, suggesting that while customers are active, they may not be responding strongly to promotional offers. This contrast highlights an opportunity to refine campaign strategies—perhaps by aligning them more closely with customer interests or timing them better within the purchase journey

**What does the distribution of product and purchase amounts reveal about customer preferences and engagement across different categories?**
"""

amounts=data.columns.tolist()[8:14]
fig = px.bar(data[amounts].sum(),
             color=amounts,
             template='plotly_dark',
             text_auto=True,
             labels={'value':'count'},
             title='Distribution of amounts of drink'
            )
fig.write_html("drink_distribution.html")
from IPython.display import display, HTML
display(HTML("drink_distribution.html"))

"""**Insights**:-


The bar chart showing the distribution of product and purchase amounts highlights clear patterns in customer behavior. Spending is highest on gold products, followed by fish and sweet items, indicating a strong preference for premium and indulgent goods. Among purchase channels, web purchases lead the way, suggesting that customers are increasingly comfortable shopping online, while catalog and deal-based purchases show moderate engagement. This mix of product interest and channel usage offers valuable clues for inventory planning, promotional focus, and channel optimization.

# **Conclusion**

dataset reveals a customer base that is predominantly:

**Well-educated,** with most holding graduation or higher degrees.

**Middle-aged adults**, with very few young adults, teens, or children represented.

**Married or in stable relationships**, though some unconventional categories like “YOLO” and “Absurd” add a playful or non-traditional flavor.

**Without children or teenagers at home**, which correlates with higher average income levels.

💰 Income Insights
Education is a strong predictor of income: PhD holders earn the most, followed by Master’s and Graduation.

Households without kids have significantly higher income than those with children.

Interestingly, households with more teenagers show slightly higher income, possibly reflecting career maturity or dual-income families.

Marital status also influences income, with “Absurd” and “Widow” categories showing surprisingly high averages.

🛍️ Purchasing Behavior
Store purchases and web visits dominate, indicating strong engagement through physical and digital channels.

Spending is highest on gold products, followed by fish and sweet items—suggesting a taste for premium and indulgent goods.

Campaign acceptance rates are low overall, with Campaigns 3, 4, and 5 performing slightly better. This signals room for improvement in targeting and messaging.

🔗 Behavioral Correlations
Spending across categories (wine, meat, gold) is positively correlated, hinting at a segment of high-value customers with broad purchasing tendencies.

Web and catalog purchases align with spending, suggesting that digital channels are effective for reaching active buyers.

Frequent web visits without purchases may indicate browsing behavior or low conversion—an opportunity for retargeting or UX optimization.

🎯 Strategic Takeaways
Segment by education and household structure to tailor product offerings and pricing.

Refine campaign targeting using behavioral clusters rather than broad demographics.

Leverage digital channels for high-value customers, but optimize conversion paths for browsers.

Promote premium products to child-free, highly educated segments with higher disposable income.

Use humor or unconventional messaging to engage fringe categories like “YOLO” and “Absurd,” if they represent real personas.
"""